language: go
sudo: false
notifications:
  email: false

go:
  - 1.9

install:
  - npm install -g codeclimate-test-reporter
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/onsi/ginkgo/ginkgo
  - dep ensure

script:
  - ginkgo -v -r
  - ./coverage.sh

after_success:
  - codeclimate-test-reporter < coverage.txt